name: Build Android APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install buildozer
        # Install dependencies for Buildozer (e.g., Cython, kivy, etc.)
        pip install cython kivy

    - name: Install Android SDK Build-Tools
      run: |
        export ANDROID_HOME=$HOME/.buildozer/android/platform/android-sdk
        export PATH=$ANDROID_HOME/tools:$ANDROID_HOME/tools/bin:$ANDROID_HOME/platform-tools:$PATH
        mkdir -p $ANDROID_HOME
        yes | sdkmanager --licenses
        sdkmanager "platforms;android-33" "build-tools;34.0.0" "platform-tools"

    - name: Set up Buildozer for Android
      run: |
        buildozer init  # Initialize Buildozer if not already done
        # Check if you have a custom buildozer.spec file for your project
        # If so, it will be picked up automatically, but make sure it's in the right directory.
      
    - name: Build APK with Buildozer
      run: |
        buildozer android debug
